### ISSUE TITLE
Names not set for farmland added by mod

### ISSUE THREAD

**Issue by prismflasher** [Thomas107500/Adaptive-Agriculture-1.15#2]
In waila, nei, and the vanilla creative interface, the new types of farmland added by the mod display with names like "block.adaptive_agriculture.infertile_farmland" etc. The untilled forms show proper names, as well as the cover crop seeds.

**Comment by Thomas107500** [comment]
Ok got it, Thank you for posting it here :D

**Comment by Thomas107500** [comment]
Ok bug should be fixed on the latest release :D
